import { useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import API from '../api'
import { toast } from '../components/Toast'

export default function CompareTab() {
  const token = localStorage.getItem('access_token')
  const [title1, setTitle1] = useState('')
  const [title2, setTitle2] = useState('')
  const [text1, setText1] = useState('')
  const [text2, setText2] = useState('')
  const [drop1, setDrop1] = useState('Click to upload PDF/DOCX')
  const [drop2, setDrop2] = useState('Click to upload PDF/DOCX')
  const [loading, setLoading] = useState(false)
  const [result, setResult] = useState(null)

  async function extractPdf(file, setDrop, setText, setTitle) {
    setDrop('⏳ Extracting...')
    const fd = new FormData(); fd.append('file', file)
    try {
      const res = await fetch(`${API}/extract-text`, { method: 'POST', headers: { Authorization: `Bearer ${token}` }, body: fd })
      const data = await res.json()
      setText(data.text); setDrop(`✓ ${file.name}`)
      if (!setTitle.value) setTitle(file.name.replace('.pdf', '').replace('.docx', ''))
      toast('PDF extracted!', 'success')
    } catch { setDrop('Click to upload PDF/DOCX'); toast('Extraction failed', 'error') }
  }

  async function compare() {
    if (!text1.trim() || !text2.trim()) return toast('Please paste both papers', 'error')
    setLoading(true)
    try {
      const res = await fetch(`${API}/compare`, { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` }, body: JSON.stringify({ text1, text2, title1: title1 || 'Paper 1', title2: title2 || 'Paper 2' }) })
      const data = await res.json()
      if (!res.ok) throw new Error(data.detail || 'Comparison failed')
      setResult(data); toast('Comparison complete!', 'success')
    } catch (err) { toast(err.message, 'error') }
    finally { setLoading(false) }
  }

  async function downloadPdf() {
    const res = await fetch(`${API}/export-compare`, { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` }, body: JSON.stringify({ title1: result.title1, title2: result.title2, comparison: result.comparison }) })
    const blob = await res.blob()
    const a = Object.assign(document.createElement('a'), { href: URL.createObjectURL(blob), download: `compare-${Date.now()}.pdf` })
    document.body.appendChild(a); a.click(); a.remove()
    toast('PDF Downloaded!', 'success')
  }

  function downloadTxt() {
    const content = `COMPARISON: ${result.title1} vs ${result.title2}\n${'='.repeat(50)}\n\n${result.comparison}\n\nGenerated by ResearchAI`
    const a = Object.assign(document.createElement('a'), { href: URL.createObjectURL(new Blob([content], { type: 'text/plain' })), download: `compare-${Date.now()}.txt` })
    document.body.appendChild(a); a.click(); a.remove()
    toast('Downloaded!', 'success')
  }

  return (
    <div className="max-w-6xl mx-auto px-8 py-8">
      <h2 className="section-title">⚖️ Compare Papers</h2>

      <div className="grid grid-cols-2 gap-6 mb-8">
        {[
          { n: 1, title: title1, setTitle: setTitle1, text: text1, setText: setText1, drop: drop1, setDrop: setDrop1, fileId: 'pdf1' },
          { n: 2, title: title2, setTitle: setTitle2, text: text2, setText: setText2, drop: drop2, setDrop: setDrop2, fileId: 'pdf2' },
        ].map(p => (
          <motion.div key={p.n} initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: p.n * 0.1 }}
            className="bg-card border border-border rounded-2xl p-8 hover:border-purple hover:shadow-glow transition-all">
            <h3 className="text-xl font-semibold mb-6 pb-4 border-b border-border">📄 Paper {p.n}</h3>

            <div className="mb-4">
              <label className="text-sm font-semibold block mb-2">Paper Title</label>
              <input className="input-field" placeholder={`Enter paper ${p.n} title`} value={p.title} onChange={e => p.setTitle(e.target.value)} />
            </div>

            <div className="mb-4">
              <label className="text-sm font-semibold block mb-2">Upload PDF or Paste Text</label>
              <motion.div whileHover={{ scale: 1.01 }} onClick={() => document.getElementById(p.fileId).click()}
                className="border-2 border-dashed border-border rounded-xl p-6 text-center cursor-pointer text-muted text-sm font-medium hover:border-purple hover:text-purple hover:bg-purple/5 transition-all flex flex-col items-center gap-2">
                <span className="text-2xl opacity-70">📄</span>
                <span>{p.drop}</span>
                <span className="text-xs text-muted">Max 10MB</span>
              </motion.div>
              <input id={p.fileId} type="file" accept=".pdf,.docx" hidden onChange={e => e.target.files[0] && extractPdf(e.target.files[0], p.setDrop, p.setText, { value: p.title })} />
            </div>

            <div className="flex items-center my-4 gap-3">
              <div className="flex-1 h-px bg-border" /><span className="text-muted text-xs font-semibold">OR</span><div className="flex-1 h-px bg-border" />
            </div>

            <textarea className="input-field resize-y min-h-[150px]" rows={8} placeholder={`Paste paper ${p.n} content here...`} value={p.text} onChange={e => p.setText(e.target.value)} />
            <p className="text-right text-muted text-xs mt-1">{p.text.length.toLocaleString()} characters</p>
          </motion.div>
        ))}
      </div>

      <div className="text-center mb-8">
        <motion.button whileHover={{ scale: 1.02 }} whileTap={{ scale: 0.98 }} onClick={compare} disabled={loading}
          className="grad-btn px-12 py-4 text-base">
          {loading ? '🔄 Comparing...' : '⚖️ Compare Papers'}
        </motion.button>
      </div>

      <AnimatePresence>
        {result && (
          <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }}
            className="bg-card border border-border rounded-2xl p-8">
            <div className="flex justify-between items-center mb-6 pb-4 border-b border-border flex-wrap gap-4">
              <h3 className="text-xl font-bold">📊 Comparison Results</h3>
              <div className="flex gap-3">
                <motion.button whileHover={{ scale: 1.05 }} onClick={downloadTxt} className="px-4 py-2 bg-card border-2 border-border text-white rounded-xl text-sm font-semibold hover:border-purple hover:text-purple transition-all">📄 TXT</motion.button>
                <motion.button whileHover={{ scale: 1.05 }} onClick={downloadPdf} className="px-4 py-2 bg-card border-2 border-border text-white rounded-xl text-sm font-semibold hover:border-purple hover:text-purple transition-all">📋 PDF</motion.button>
              </div>
            </div>
            <h4 className="text-purple font-bold mb-4">⚖️ {result.title1} vs {result.title2}</h4>
            <p className="text-sub leading-relaxed whitespace-pre-wrap text-sm">{result.comparison}</p>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  )
}
